<?php

namespace ContainerYFAHsgg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0fsn2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x0fsn2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x0fsn2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartService' => ['privates', 'App\\Service\\CartService', NULL, 'Cannot autowire service "App\\Service\\CartService": argument "$em" of method "__construct()" references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
        ], [
            'cartService' => 'App\\Service\\CartService',
        ]);
    }
}
