<?php

namespace ContainerZheZue5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0fsn2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x0fsn2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x0fsn2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartService' => ['privates', 'App\\Service\\CartService', NULL, 'Cannot autowire service "App\\Service\\CartService": argument "$sessionInterface" of method "__construct()" references interface "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'cartService' => 'App\\Service\\CartService',
        ]);
    }
}
