<?php

namespace ContainerZheZue5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CartService' shared autowired service.
     *
     * @return \App\Service\CartService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\CartService": argument "$sessionInterface" of method "__construct()" references interface "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
