<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpBNmN4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpBNmN4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpBNmN4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpBNmN4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXpBNmN4\App_KernelDevDebugContainer([
    'container.build_hash' => 'XpBNmN4',
    'container.build_id' => '79ff297a',
    'container.build_time' => 1686667742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpBNmN4');
