<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvzp6na\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvzp6na/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBvzp6na.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBvzp6na\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBvzp6na\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bvzp6na',
    'container.build_id' => '67ed905a',
    'container.build_time' => 1687045238,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBvzp6na');
