<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Jvolw3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Jvolw3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Jvolw3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Jvolw3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Jvolw3\App_KernelDevDebugContainer([
    'container.build_hash' => '2Jvolw3',
    'container.build_id' => '3404335b',
    'container.build_time' => 1687448822,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Jvolw3');
